name: Learn CI

on: [push]

jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Talk
        run: echo "Learning CI/CD"

      - name: Print OS name
        run: echo "This job is running on ${{ runner.os }}
