name: Learn CI

on: [push]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Talk
        run: echo "Learning CI/CD"
